export const icons = {
  auth_logo: "/icons/auth-logo.svg",
  avatar: "/icons/avatar.svg",
  delete: "/icons/delete.svg",
  discover: "/icons/discover.svg",
  edit: "/icons/edit.svg",
  empty_state: "/icons/empty-state.svg",
  forward: "/icons/forward.svg",
  hamburger: "/icons/hamburger.svg",
  headphone: "/icons/headphone.svg",
  home: "/icons/home.svg",
  logo: "/icons/logo.svg",
  microphone: "/icons/microphone.svg",
  mute: "/icons/mute.svg",
  pause: "/icons/pause.svg",
  play_gray: "/icons/play-gray.svg",
  play: "/icons/play.svg",
  profile: "/icons/profile.svg",
  random_play: "/icons/random-play.svg",
  reverse: "/icons/reverse.svg",
  right_arrow: "/icons/right-arrow.svg",
  search: "/icons/search.svg",
  three_dots: "/icons/three-dots.svg",
  unmute: "/icons/unmute.svg",
  upload_image: "/icons/upload-image.svg",
  verified: "/icons/verified.svg",
  watch: "/icons/watch.svg",
};
